docs: add api docs preview guide
strongloop/loopback-next pull request #6628
Opened 2020-10-22 16:17 UTC by jannyHou

Signed-off-by: jannyHou <juehou@ca.ibm.com>

Add more detailed steps of previewing the API docs.

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

2020-10-22 18:03 UTC, dhmlau reviewed
Thanks for updating this, @jannyHou. 
It seems like the only difference to preview the API docs vs other docs pages is to run the build and `npm run tsdocs`. Maybe we can put it as part of the "Previewing loopback-next docs only" section?

2020-10-22 18:03 UTC, dhmlau commented on docs/site/DEVELOPING.md
> +To modify the documentation and preview the changes, you should rebuild the
```suggestion
To modify the API documentation and preview the changes, you should rebuild the
```

2020-10-22 19:13 UTC, emonddr commented on docs/site/DEVELOPING.md
> +package and run `npm run tsdocs`. For example, some API doc are changed in
Start the `For example` in a new paragraph.

2020-10-22 19:26 UTC, jannyHou commented
@dhmlau @emonddr Thanks for review. Previewing other docs is actually quite different from my experience. For example:

- no need to rebuild the package, cuz the changes are inside `/docs/pages/*.md`.
- must run `npm run docs:prepare` to fetch the changed docs. But docs change doesn't need that step.

It's very hard to figure out the right sequence for running those commands without a guide.

2020-10-22 19:27 UTC, emonddr requested changes
Hi Janny, it is great to document these steps, thank you.
Just a few tiny comments :)

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +package and run `npm run tsdocs`. For example, some API doc are changed in
```suggestion
For example, if some API documentation changes have occurred in `/loopback-next/packages/core`, and you wish to preview them, perform the following steps:
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +npm run clean
add a newline here

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +# new API docs.
```suggestion

```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +# Rebuild the package, so that the compiled dist files contain
```suggestion
# Rebuild the package, so that the compiled dist files contain the new API documentation
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +Run the following commands from root dir `/loopback-next`:
```suggestion
Run the following commands within the root directory `/loopback-next`:
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +step 3 - preview the API docs on browser
```suggestion
step 3 - preview the API documentation in a browser
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +Stay in the root dir and run the following commands:
```suggestion
Stay in the root directory and run the following commands:
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +# Fetch the new API docs into `/docs/_preview`
```suggestion
# Fetch the new API documentation into `/docs/_preview`
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +# Start the docs preview server
```suggestion
# Start the documentation preview server
```

2020-10-22 19:27 UTC, emonddr commented on docs/site/DEVELOPING.md
> +Go to http://127.0.0.1:4001 in browser you will see the new API documentation.
```suggestion
Go to http://127.0.0.1:4001 in a browser, and you will see the new API documentation.
```

2020-10-22 19:40 UTC, dhmlau commented
According to https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#previewing-loopback-next-docs-only, previewing docs also needs `npm run docs:prepare`.  That means:

Steps to preview API docs:
```
npm install
npm run build
npm run tsdocs
npm run docs:prepare
npm run docs: start
```

Steps to preview other docs (md files):
```
npm run docs:prepare
npm run docs:start
```

2020-10-22 19:45 UTC, jannyHou commented on docs/site/DEVELOPING.md
> +npm run clean
hmm why add a new line?

2020-10-22 19:48 UTC, jannyHou commented
@dhmlau Previewing lb-next docs only require running "npm run docs:prepare" ONLY ONCE. Copying the doc here:

> As the initial setup, run the following command once, before you start making documentation changes:
$ npm run docs:prepare
Whenever you want to (re)render documentation, just (re)start the following command:
$ npm run docs:start

But previewing API docs require running "npm run docs:prepare" EVERYTIME.

2020-10-22 19:50 UTC, jannyHou commented
But your link reminds me the API doc preview should be with section "previewing-loopback-next-docs-only".

2020-10-22 20:09 UTC, dhmlau commented
> Previewing lb-next docs require running "npm run docs:prepare" ONLY ONCE. 
> ...
> But previewing API docs require running "npm run docs:prepare" EVERYTIME.

I see. I didn't realize the difference. 
I'm good either way whether we have a separate section for previewing the API docs. Just wanna point out the similarity in the steps. If you think it's clearer to separate out the steps, please feel free. Thanks.

2020-10-22 20:49 UTC, jannyHou commented on docs/site/DEVELOPING.md
> +# new API docs.
deleting the contents?

2020-10-22 21:24 UTC, jannyHou commented
I realized the API Documentation is right after "previewing-loopback-next-docs-only", so I keep the position as is.

2020-10-22 23:09 UTC, dhmlau approved these changes

2020-10-23 15:41 UTC, emonddr approved these changes
I approve, but please fix one last thing, with my latest suggestion. thx.

2020-10-23 15:41 UTC, emonddr commented on docs/site/DEVELOPING.md
> +package and run `npm run tsdocs`. For example, some API doc changes have
```suggestion
package and run `npm run tsdocs`. For example, if some API documentation changes have
```

2020-10-23 16:00 UTC, merged