Update Binding.md
strongloop/loopback-next pull request #6783
Opened 2020-11-14 08:57 UTC by mrfarhadir

Removing extra "</div>"

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

2020-11-16 00:50 UTC, dhmlau requested changes
@mrfarhadir, thanks for your PR. 
I'm afraid that the quote is needed because it's part of the content for the note. Having said that, there's some formatting issue around that note. It seems like we can fix it by removing the indent for the note.html. 

Here is the instruction to preview docs locally: https://github.com/strongloop/loopback-next/blob/master/docs/site/DEVELOPING.md#previewing-loopback-next-docs-only

2020-11-16 00:55 UTC, dhmlau commented
Please also sign your commit by following the instructions: https://loopback.io/doc/en/contrib/code-contrib.html. Thanks.

2020-11-16 06:43 UTC, mrfarhadir commented
![image](https://user-images.githubusercontent.com/26628753/99220591-3040f900-27f4-11eb-82b3-b1ff15c18089.png)
I just wanted to notice and fix that extra ```/div ```

So If it could be done by your self, I'll remove to this PR.

2020-11-17 00:53 UTC, dhmlau commented
superseded by #6795.

2020-11-17 00:53 UTC, closed without merging