docs: tip to intercept all queries
strongloop/loopback-next pull request #6849
Opened 2020-11-26 13:52 UTC by QPierre1

Share a workaround to intercept all requests

re #6099

Signed-off-by: quentin <31855566+QPierre1@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

2020-11-26 14:19 UTC, achrinza commented
Thanks for the pull request! Please refrain from opening duplicate PRa and consider using `git rebase` and `git push --force-with-lease` to fix the git history.

2020-12-16 12:27 UTC, achrinza requested changes

2020-12-16 12:27 UTC, achrinza commented on docs/site/Interceptor.md
> +{% include tip.html content="If you need to intercept all requests, including these destinated to a LB3 mounted app, you can use [a Loopback middleware](https://loopback.io/doc/en/lb4/Middleware.html
Apologies for missing this PR, may I suggest that we reference the Markdown file directly? The docs generator will automatically convert it into the relevant URLs:
```suggestion
{% include tip.html content="If you need to intercept all requests, including these destinated to a LB3 mounted app, you can use a [LoopBack Middleware](./Middleware.md#loopback-style-middleware)" %}
```

2020-12-16 14:45 UTC, QPierre1 commented
Yes

2020-12-16 14:47 UTC, merged

2020-12-16 14:47 UTC, achrinza commented
Thanks for the Pull Request! It's been merged to master.