feat: allow one strategy to fail the authentication process
strongloop/loopback-next pull request #7330
Opened 2021-03-29 03:01 UTC by raymondfeng

BREAKING CHANGE: The current code allows a strategy to throw an error but
it only fails the authentication process if other ones either skip or fail.
This behavior does not allow a strategy to abort the process. With this PR,
a strategy can decide how to proceed as follows:

1. Return normal user profile or redirect to finish the authentication
2. Return undefined/null to continue with next one
3. Throw an error to abort the process

Signed-off-by: Raymond Feng <enjoyjava@gmail.com>

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

2021-03-29 12:19 UTC, nflaig reviewed
@raymondfeng I feel like this makes the authentication process a bit unclear. Returning undefined/null to continue with next one does not feel intuitive to me. I previously also suggested that we might allow strategies to not return a userprofile or redirect and still be considered successful. This would make sense for strategies which do not involve a user e.g. api key, ip whitelisting.

I also have a hard time finding a usecase where you would want a logical AND for authentication stragies because you would rather implement one strategie which does all the required checks instead of splitting those into different strategies. Maybe you could provide an example where chaining of auth strategies makes sense, this would probably help to better understand the usecase.

2021-03-29 14:59 UTC, raymondfeng commented
@nflaig I have a few use cases that can be seen as `AND` and `OR` of multiple strategies.

1. Authenticate the client application AND authenticate the user
2. Allow JWT OR a signature based authentication
3. Allow an `anonymous` to catch unauthenticated cases so that authorization can make a decision.

With that context, I need a way for a strategy to instruct `@loopback/authentication` for the following 3 options:

1. The strategy is successful and let's be done.
2. The strategy fails and let's abort
3. The strategy wants to fall back to another strategy

The authentication should only check the credentials and establish security context for authorization to make the call.  

Also forcing a strategy to return `UserProfile` is a bit limited as strategies can establish more than one principals and it would be more ideal to return a `Subject` that serves as a container of security context. But I can work around the issue by binding extract values to the request context so that my authorization can pick them up.

2021-03-29 15:38 UTC, nflaig commented
@raymondfeng so basically as far as I can see only _1. Authenticate the client application AND authenticate the user_ is currently not possible by using 2 different strategies but shouldn't the proper way to do this rather be to implement it as one strategy if you always need to authenticate the client app and the user?

The main issue I am having with adding the changes in the PR is that it is no longer transparent how the authentication process works based on just looking at the `@authenticate` decorator unless you exactly know implementation details of the strategies.

> Also forcing a strategy to return UserProfile is a bit limited as strategies can establish more than one principals and it would be more ideal to return a Subject that serves as a container of security context. But I can work around the issue by binding extract values to the request context so that my authorization can pick them up.

Totally agreed, userprofile is way to specific

2021-03-29 16:06 UTC, raymondfeng commented
With the current code, I cannot implement `The strategy fails and let's abort`.

2021-03-29 16:11 UTC, raymondfeng commented
> The main issue I am having with adding the changes in the PR is that it is no longer transparent how the authentication process works based on just looking at the @authenticate decorator unless you exactly know implementation details of the strategies.

I would argue the current design is NOT intuitive when a strategy throws an exception to fail the process as it's ignored unless other strategies decide to fail as well.

2021-03-29 16:30 UTC, nflaig commented
@raymondfeng well basically the idea with multiple strategies is to allow multiple ones. I you need `The strategy fails and let's abort` you should not allow multiple strategies. I do also understand your point of view but my problem is that it that it is no longer possible to comprehend the authentication logic by just looking at the `@authenticate` decorator. Let's assume we have a decorator such as `@authenticate("bearer", "basic")`, without knowing how the strategies are implemented I am safe to assume that this means allow either bearer token auth or basic auth. If we allow this chaining behavior I would have to look into the implementation of the strategies to figure out if it now requires either of them to succeed or both of them because it depends now on the return value of the strategie.

A possible to solution could be to allow the user to specify if multiple strategies should be executed as a logical AND or OR.

> I would argue the current design is NOT intuitive when a strategy throws an exception to fail the process as it's ignored unless other strategies decide to fail as well.

Well, that's because it is a logical OR, only one strategy has to succeed. I am not sure what most users expect to be honest but since the passport implementation is based on the same logic I am assuming they expect a logical OR if they specify multiple strategies (just my assumption).

Also another problem that just came to my mind, wouldn't this chaining behavior of strategies also mean that if you change the order of the strategies in the decorator it would also behavior changes?

2021-03-29 16:47 UTC, raymondfeng commented
@nflaig Even for `OR`, if one of the strategy recognizes the scheme (such as `Basic`) but the username/password does not match, the authentication should be allowed to fail without checking other strategies. I wonder why a strategy throws an error instead of returning `undefined` if it assumes other strategies can succeed.

2021-03-29 17:04 UTC, nflaig commented
@raymondfeng

> For example, if I decorate a method with @authenticate('bearer', 'basic'), I would assume the authentication fails if a bearer token is expired. This is different from that case where authorization header starts with Basic as the bearer strategy will just skip.

That does make sense but I am not sure how this could be made transparent to the end user who just uses existing strategies without knowing implementation details. Also if we assume that most users won't implement their own auth strategies but use existing passport strategies the example you mentioned does not exist. This is due to the fact that the [passport implementation](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L94) works almost exactly the same as the current loopback implementation with some minor differences and all existing strategies are implemented according to this behavior.

Probably, someone else has to give some feedback/review the PR, I am not yet convinced by the change :sweat_smile:

2021-03-29 17:10 UTC, raymondfeng commented
@nflaig Thank you for the pointer to passport's middleware implementation. Actually one of the motivations of LB4 having its own authentication is to remove the frictions and barriers of Passport which is tied to Express's inflexible middleware chain. The passport is still very much callback based and it uses `req` to pass information. But even with passport, the order of strategies still matters as it says in the comment.

2021-03-29 17:48 UTC, nflaig commented
> But even with passport, the order of strategies still matters as it says in the comment.

yeah but in the case of passport it does not change the authentication outcome it just changes the error message if all strategies fail since it will only "flash" the message of the strategy that first failed.

2021-03-30 05:57 UTC, raymondfeng commented
@nflaig I'm really looking for the veto right by one of the strategies and you seem to agree that `bearer token expiration` is one of such valid use cases. Do you have an alternative proposal to implement such feature?

2021-03-30 07:32 UTC, nflaig commented
@raymondfeng not really sure what would be a proper way to do this without causing to much breaking changes but for example in passport the strategies call the `this.fail` to indicate an authentication failure, maybe we could implement something similar and also include the `skip/abstain` behavior

since all existing lb4 strategies are based on `returning something = success` and `throwing an error = failure` this seems to be a major breaking change, also really not sure how a proper implementation would look like

2021-03-30 15:38 UTC, raymondfeng commented
@nflaig Instead of changing the current behavior, I now introduce `failOnError` for the authentication component to opt in the new one. This is consistent with passport's `failOnError` option. PTAL.

2021-03-30 16:05 UTC, nflaig commented
@raymondfeng

>This is consistent with passport's failOnError option.

could you please point me this, I am not able to find it in the passport implementation

2021-03-30 16:07 UTC, raymondfeng commented
See https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L171

2021-03-30 16:28 UTC, nflaig requested changes

2021-03-30 16:28 UTC, nflaig commented on packages/authentication/src/types.ts
> +   * throwing an error if `allowsStrategyToAbort` is set to `true`. By default,
@raymondfeng should be `failOnError` instead of `allowsStrategyToAbort`

2021-03-30 16:32 UTC, nflaig commented
@raymondfeng another feature this PR adds is to allow a strategy to just continue the authentication chain by returning `null/undefined`. This should probably also be documented somehow but I guess there are not existing strategies that do this since it would have thrown an error as of now.

2021-03-30 18:28 UTC, raymondfeng commented
> another feature this PR adds is to allow a strategy to just continue the authentication chain by returning null/undefined

That's the existing behavior, isn't it?

2021-03-30 18:44 UTC, nflaig commented
@raymondfeng 
> That's the existing behavior, isn't it?
yes you are right it would always count as a failure of the strategy, I guess one problem of the existing logic is that there is not differentiation between an Error of some sort and a strategy signaling failure. The solution passport implements for this is quite good in my opinion but hard to get to work since from the beginning all LB4 auth strategies used errors to indicate failure.

2021-03-30 18:53 UTC, nflaig approved these changes

2021-03-30 19:49 UTC, merged